### ISSUE TITLE
Support for mouse deconvolution

### ISSUE THREAD

**Issue by FFinotello** [omnideconv/immunedeconv#105]
When the new release is ready, we should:

- Clarify in the README page that human methods can be also used on mouse data;
-  Showcase a human-to-mouse example in the vignette;
- Reply to [this discussion](https://github.com/omnideconv/immunedeconv/discussions/78).

**Comment by LorenzoMerotto** [comment]
1 - The conversion of methods should be already mentioned in the README
2 - In the mouse vignette hte human-mpouse conversion is presented. However I had to leave it as normal code-text without showcasing some results since the Ensembl servers are down more often than not, and the functions result in errors when hte vignette is built
3 - The mouse methods are already accessible so I'll just wait for the new release and reply


P.S. The mouse vignette is ready but for some reason does not appear at: https://omnideconv.org/immunedeconv/index.html
@grst is there something that I can do to update the website?

**Comment by grst** [comment]
website should be up to date now. Still need to improve the automatic deployment at some point, but that's tracked in #100.

**Comment by grst** [comment]
@LorenzoMerotto  can this be closed?
